"""Build Baseten training data for spec-to-CAD SFT (and the RL prompt set).

  uv run python -m cadabra.cad.build_sft

Writes training/data/{train,val}.jsonl in TRL's conversational prompt/completion format (loss on the code only)
and training/data/grpo.jsonl (harder prompts with their reference code, for the RL stage). Also copies the
geometry checker into training/cadcheck/ so the RL job can score rollouts. Every prompt is exactly what the
benchmark sends a zero-shot lane, so training and evaluation match.
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
from collections import Counter

from ..config import ROOT
from ..data import read_jsonl, split_by_source, write_jsonl
from . import prompts

DATA = ROOT / "data" / "cad"
OUT = ROOT / "training" / "data"


def example(rec: dict) -> dict:
    return {
        "prompt": prompts.messages(rec["spec"]),
        "completion": [{"role": "assistant", "content": prompts.completion(rec["gold_code"])}],
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--val-frac", type=float, default=0.02)
    ap.add_argument("--max-chars", type=int, default=13000, help="drop examples that could overflow MAX_LEN=4096 tokens")
    ap.add_argument("--grpo-size", type=int, default=1200)
    ap.add_argument("--seed", type=int, default=11)
    args = ap.parse_args()

    train = read_jsonl(DATA / "train.jsonl")
    bench_sources = {r["source_id"] for r in read_jsonl(DATA / "bench.jsonl")}
    shot_ids = {r["id"] for r in read_jsonl(DATA / "shots.jsonl")}
    dropped = Counter()
    rows = []
    for rec in train:
        if rec["source_id"] in bench_sources:
            dropped["source in bench (leakage guard)"] += 1
            continue
        if rec["id"] in shot_ids:
            dropped["used as a worked example"] += 1
            continue
        ex = example(rec)
        if sum(len(m["content"]) for m in ex["prompt"] + ex["completion"]) > args.max_chars:
            dropped["too long"] += 1
            continue
        rows.append({**rec, **ex})

    fit, val = split_by_source(rows, args.val_frac, seed=args.seed)
    OUT.mkdir(parents=True, exist_ok=True)
    write_jsonl(OUT / "train.jsonl", [{"prompt": r["prompt"], "completion": r["completion"]} for r in fit])
    write_jsonl(OUT / "val.jsonl", [{"prompt": r["prompt"], "completion": r["completion"]} for r in val])

    # RL prompts: oversample what SFT finds hard (multi-part, many faces); keep the reference for the reward.
    rng = random.Random(args.seed)
    hard = [r for r in fit if r["n_parts"] > 1 or r.get("n_faces", 0) >= 10]
    easy = [r for r in fit if r not in hard]
    k_hard = min(len(hard), int(args.grpo_size * 0.6))
    picked = rng.sample(hard, k_hard) + rng.sample(easy, min(len(easy), args.grpo_size - k_hard))
    rng.shuffle(picked)
    write_jsonl(OUT / "grpo.jsonl", [{"prompt": r["prompt"], "gold_code": r["gold_code"]} for r in picked])

    cadcheck = ROOT / "training" / "cadcheck"
    cadcheck.mkdir(exist_ok=True)
    for name in ("geometry.py", "pool.py"):
        shutil.copy(ROOT / "cadabra" / "cad" / name, cadcheck / name)
    (cadcheck / "__init__.py").write_text('"""Copy of cadabra/cad geometry checker for the RL reward (generated by build_sft)."""\n')

    chars = [sum(len(m["content"]) for m in r["prompt"] + r["completion"]) for r in fit]
    stats = {
        "train": len(fit),
        "val": len(val),
        "grpo_prompts": len(picked),
        "grpo_hard_share": round(k_hard / max(len(picked), 1), 2),
        "dropped": dict(dropped),
        "chars_per_example_p50_p95_max": [sorted(chars)[len(chars) // 2], sorted(chars)[int(len(chars) * 0.95)], max(chars)],
        "approx_train_tokens_per_epoch": int(sum(chars) / 3.6),
    }
    (OUT / "stats.json").write_text(json.dumps(stats, indent=2))
    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
